### ISSUE TITLE
ndt_omp_ = ndtInit(ndt_resolution);    core dumped

### ISSUE THREAD

**Issue by qqq1mmm** [APRIL-ZJU/lidar_IMU_calib#12]
![image](https://user-images.githubusercontent.com/46803794/99068041-bd166780-25e6-11eb-8748-d84717049c6d.png)
[li_calib_gui-2] process has died [pid 2414, exit code -6, cmd /home/ubuntu/catkin_LtoI/devel/lib/li_calib/li_calib_gui __name:=li_calib_gui __log:=/home/ubuntu/.ros/log/1b21c2be-25a3-11eb-bf5b-00163e4b6f10/li_calib_gui-2.log].
log file: /home/ubuntu/.ros/log/1b21c2be-25a3-11eb-bf5b-00163e4b6f10/li_calib_gui-2*.log

**Comment by qqq1mmm** [comment]
![image](https://user-images.githubusercontent.com/46803794/99638065-ae193480-2a80-11eb-9ae9-b8f3b5456689.png)

**Comment by Jitaseal** [comment]
How do you solve the first problem, I also encountered this problem.

**Comment by qqq1mmm** [comment]
I think you can uninstall the pcl that you have installed previously.
