### ISSUE TITLE
imu's params  overwritten

### ISSUE THREAD

**Issue by narutojxl** [APRIL-ZJU/lidar_IMU_calib#2]
Hi author @icameling,  
The most details  in paper are realized and encapsulated in [modified Kontiki](https://github.com/APRIL-ZJU/Kontiki/tree/909a1fc1be0edffc4aec13b78802a4cc9a3a2770) and [lidar_surfel_point.h](https://github.com/APRIL-ZJU/Kontiki/blob/909a1fc1be/include/kontiki/measurements/lidar_surfel_point.h),  Maybe i will take some more time to learn this Toolkit to better understand paper. Thanks for your this excellent work! :) 
In [CalibParamManager ctor](https://github.com/APRIL-ZJU/lidar_IMU_calib/blob/master/include/core/calibration.hpp),  acc, gyro and laser weight used in trajectory_manager.cpp is overwritten by const value.
>
    // fine-tuned parameter
    global_opt_gyro_weight = 28.0;
    global_opt_acce_weight = 18.5;
    global_opt_lidar_weight = 10.0; 

When use my own imu, its price is about dozens of RMB, how to set three params? Thanks a lot!
Best

**Comment by icameling** [comment]
Now the output error statistics are the original errors, such as point-to-surfel, the errors between IMU measurements and derivatives of estimated trajectory, they are all unweighted.
If you use different types of IMUs, we suggest to output the weighted error, that is, the normalized error, and check out if the magnitude of the error and the noise amplitude are consistent.

**Comment by narutojxl** [comment]
Thanks for your detailed reply :), close it now.
