### ISSUE TITLE
./src/lidar_IMU_calib/calib.sh  [Initialization] fails

### ISSUE THREAD

**Issue by ZhaZhaJ** [APRIL-ZJU/lidar_IMU_calib#28]
![image](https://user-images.githubusercontent.com/64353489/128154284-5e068dac-8112-4409-bcbe-3e3fc7360a46.png)

**Comment by leonshaw06** [comment]
You should click the Initialization button again and again until the cov exceeds 0.25.

**Comment by ZhaZhaJ** [comment]
> You should click the Initialization button again and again until the cov exceeds 0.25.

thanks，I have solved this problem through Reinstall the system.
