### ISSUE TITLE
ERROR: cannot launch node of type [li_calib/li_calib_gui]

### ISSUE THREAD

**Issue by jpqrest** [APRIL-ZJU/lidar_IMU_calib#32]
Hi,

I am trying to use clidar_IMU_calib to align my lidar and IMU, however, after building the project and loading li_calib_gui node with command: ./src/lidar_IMU_calib/calib.sh, I got following message:

... logging to /home/neousys/.ros/log/5225dbb0-3b87-11ec-a470-0028f8cacfa1/roslaunch-nuvo-jl-19945.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nuvo-jl:37309/

SUMMARY
========

PARAMETERS
 * /li_calib_gui/LidarModel: VLP_16
 * /li_calib_gui/bag_durr: 30.0
 * /li_calib_gui/bag_start: 1.0
 * /li_calib_gui/ndtResolution: 0.5
 * /li_calib_gui/path_bag: /home/neousys/ros...
 * /li_calib_gui/scan4map: 15.0
 * /li_calib_gui/show_ui: False
 * /li_calib_gui/time_offset_padding: 0.015
 * /li_calib_gui/topic_imu: /imu1/raw/data_wi...
 * /li_calib_gui/topic_lidar: /velodyne_packets
 * /rosdistro: melodic
 * /rosversion: 1.14.12

NODES
  /
    li_calib_gui (li_calib/li_calib_gui)

auto-starting new master
process[master]: started with pid [19955]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5225dbb0-3b87-11ec-a470-0028f8cacfa1
process[rosout-1]: started with pid [19966]
started core service [/rosout]
ERROR: cannot launch node of type [li_calib/li_calib_gui]: Cannot locate node of type [li_calib_gui] in package [li_calib]. Make sure file exists in package path and permission is set to executable (chmod +x)

**Comment by dingkwang** [comment]
Hi, @jpqrest  I have the same error using the provided data. How did you resolve it?
