### ISSUE TITLE
How to make /imu/data_sync data?

### ISSUE THREAD

**Issue by Taeyoung96** [APRIL-ZJU/lidar_IMU_calib#50]
@icameling   
Thanks for your great work!  
I have some questions about this tool with the Custom ROS bag file.  

I have only topics named `/velodyne_points` and `imu/data`.  
Is this algorithm works with these topics without `imu/data_sync`?  

If not, How to make `imu/data_sync` topic?  
I'd appreciate your help.  

Thanks,

**Comment by yinhaosen** [comment]
I think you need to synchronize lidar and imu data. There are some ways of doing it such as from hardware level or simple synchronization algorithms.

**Comment by Taeyoung96** [comment]
@yinhaosen   
Thanks for your reply.  
Is there any recommended simple synchronization algorithm?

**Comment by yinhaosen** [comment]
ROS has native support interface google `message_filters::sync`.
