### ISSUE TITLE
is there any reference for vlp_common.h?

### ISSUE THREAD

**Issue by petersong1905** [APRIL-ZJU/lidar_IMU_calib#6]
thx for your transcendent work!

but i don't konw the following concept, is there any paper or document ?

1. float vert_correction[16] // is it the tan of corresponding scan_mapping_16[]?

2. there 're two void unpack_scan() reload in VelodyneCorrection,is velodyne_msgs::VelodyneScan::ConstPtr  more accurate than sensor_msgs::PointCloud2::ConstPtr ?

thanks you so much!

**Comment by icameling** [comment]
- I think your questions could be summarized into one question, that is, how to accurately get the timestamp of each lidar point.

- For Velodyne-16,  you could refer to it's [user manual](https://velodynelidar.com/downloads/) (choose Puck Manual). Here is a snap from chapter 9 of that user manual and it coincides with the code. Note that, the timestamps of Velodyne messages `velodyne_msgs::VelodyneScan::ConstPtr`  have been preprocessed according to the hardware time synchronization flag.

![timestamp-vlp](https://user-images.githubusercontent.com/12575288/95738493-e8422a00-0cbb-11eb-8a4c-e2b316671840.png)


- Additionally, the second  [unpack_scan](https://github.com/APRIL-ZJU/lidar_IMU_calib/blob/master/include/utils/vlp_common.h#L152) function is for simulation data.

**Comment by petersong1905** [comment]
@icameling  thanks for your advices.
 i found full_firing_cycle and single_firing  in following github ,and it works now.
[https://github.com/ros-drivers/velodyne](url)
